PYTHON=${PYTHON:-/usr/local/bin/python}

PRODROOT=${PRODROOT:-/full-path/internship-project}
PYSRCROOT=${PYSRCROOT:-${PRODROOT}/src/python}
PYTHONPATH=${PYTHONPATH:-${PYSRCROOT}}
CONFROOT=${CONFROOT:-${PRODROOT}/etc}
PYTHON_EGG_CACHE=${PYTHON_EGG_CACHE:-/tmp/.python-eggs}
export PRODROOT PYSRCROOT PYTHONPATH CONFROOT PYTHON_EGG_CACHE

${PYTHON} ${PYSRCROOT}/monitors/processes_threshold.py $*
